import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; 
import { Providers } from "@/lib/providers";

// Source - https://stackoverflow.com/a
// Posted by sundayonah, modified by community. See post 'Timeline' for change history
// Retrieved 2026-01-23, License - CC BY-SA 4.0

  // layout.tsx
  

  export default function RootLayout({
   children,
  }: {
   children: React.ReactNode;
  }) {
   return (
      <html lang="en">
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
   );
  }


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

